apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercises
  template:
    metadata:
      labels:
        app: exercises
    spec:
      containers:
      - name: exercises
        image: ${DOCKER_USERNAME}/exercises:latest
        ports:
          - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: exercises
spec:
  selector:
    app: exercises
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
