apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
      - name: history
        image: ${DOCKER_USERNAME}/history:latest
        ports:
          - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: history
spec:
  selector:
    app: history
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
