apiVersion: apps/v1
kind: Deployment
metadata:
  name: onermcalculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onermcalculator
  template:
    metadata:
      labels:
        app: onermcalculator
    spec:
      containers:
      - name: onermcalculator
        image: ${DOCKER_USERNAME}/onermcalculator:latest
        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: onermcalculator
spec:
  selector:
    app: onermcalculator
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
