services:

  onermcalculator:
    container_name: onermcalculator
    build:
      context: ../Express
    depends_on:
      - history

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../FrontEnd/gym-app/build:/usr/share/nginx/html
    depends_on:
      - onermcalculator

  history:
    container_name: history
    build:
      context: ../redis
    depends_on:
      - redis

  exercises:
    container_name: exercises
    build:
      context: ../Mongo
    depends_on:
      - mongo

  redis:
    container_name: redis
    image: redis:alpine

  mongo:
    container_name: mongo
    image: mongo:latest

